markdown: rdiscount
highlighter: pygments
permalink: /posts/:title
future: true
kramdown:
  input: GFM
github: thehackerwithin
url: http://thehackerwithin.github.com/berkeley 
name: Hacker Within
chapter: Berkeley
description: An initial blog and site for THW at UCB
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin

